
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package com.example.boxworld.LexSint;

import java_cup.runtime.*;
import java.util.*;
import com.example.boxworld.Mov.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\043\000\002\002\003\000\002\002\004\000\002\002" +
    "\003\000\002\021\004\000\002\021\003\000\002\003\003" +
    "\000\002\003\003\000\002\022\003\000\002\022\003\000" +
    "\002\022\003\000\002\022\003\000\002\023\004\000\002" +
    "\013\006\000\002\010\005\000\002\024\006\000\002\024" +
    "\006\000\002\011\003\000\002\015\005\000\002\015\005" +
    "\000\002\015\003\000\002\016\005\000\002\016\005\000" +
    "\002\016\004\000\002\016\003\000\002\017\005\000\002" +
    "\017\006\000\002\017\006\000\002\017\003\000\002\020" +
    "\003\000\002\020\003\000\002\020\003\000\002\020\005" +
    "\000\002\025\005\000\002\026\011\000\002\026\011" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\112\000\016\004\020\010\011\011\012\015\015\024" +
    "\004\027\016\001\002\000\004\005\ufff8\001\002\000\004" +
    "\002\uffff\001\002\000\004\005\042\001\002\000\016\002" +
    "\001\004\020\010\011\011\012\015\015\024\004\001\002" +
    "\000\004\002\112\001\002\000\004\005\ufff7\001\002\000" +
    "\012\004\020\010\011\015\015\024\004\001\002\000\016" +
    "\002\ufffb\004\ufffb\010\ufffb\011\ufffb\015\ufffb\024\ufffb\001" +
    "\002\000\016\002\ufffd\004\ufffd\010\ufffd\011\ufffd\015\ufffd" +
    "\024\ufffd\001\002\000\004\005\ufff9\001\002\000\004\031" +
    "\022\001\002\000\016\002\ufffc\004\ufffc\010\ufffc\011\ufffc" +
    "\015\ufffc\024\ufffc\001\002\000\004\005\ufffa\001\002\000" +
    "\004\030\037\001\002\000\006\032\024\035\023\001\002" +
    "\000\004\031\032\001\002\000\004\031\025\001\002\000" +
    "\004\026\026\001\002\000\004\031\027\001\002\000\004" +
    "\033\030\001\002\000\004\031\031\001\002\000\004\030" +
    "\uffdf\001\002\000\004\026\033\001\002\000\004\031\034" +
    "\001\002\000\004\034\035\001\002\000\004\031\036\001" +
    "\002\000\004\030\uffe0\001\002\000\004\002\uffe1\001\002" +
    "\000\004\005\042\001\002\000\016\002\ufff4\004\ufff4\010" +
    "\ufff4\011\ufff4\015\ufff4\024\ufff4\001\002\000\020\005\044" +
    "\007\050\012\056\013\045\017\057\023\047\025\043\001" +
    "\002\000\016\006\uffe4\016\uffe4\017\uffe4\020\uffe4\021\uffe4" +
    "\022\uffe4\001\002\000\020\005\044\007\050\012\056\013" +
    "\045\017\057\023\047\025\043\001\002\000\004\005\105" +
    "\001\002\000\016\006\uffe3\016\uffe3\017\uffe3\020\uffe3\021" +
    "\uffe3\022\uffe3\001\002\000\004\005\102\001\002\000\016" +
    "\006\uffe5\016\uffe5\017\uffe5\020\uffe5\021\uffe5\022\uffe5\001" +
    "\002\000\004\006\100\001\002\000\016\006\uffe6\016\uffe6" +
    "\017\uffe6\020\uffe6\021\uffe6\022\074\001\002\000\014\006" +
    "\uffea\016\uffea\017\uffea\020\uffea\021\uffea\001\002\000\014" +
    "\006\uffee\016\uffee\017\uffee\020\070\021\067\001\002\000" +
    "\010\006\ufff1\016\064\017\063\001\002\000\004\005\061" +
    "\001\002\000\016\005\044\007\050\012\056\013\045\023" +
    "\047\025\043\001\002\000\014\006\uffeb\016\uffeb\017\uffeb" +
    "\020\uffeb\021\uffeb\001\002\000\020\005\044\007\050\012" +
    "\056\013\045\017\057\023\047\025\043\001\002\000\010" +
    "\006\065\016\064\017\063\001\002\000\020\005\044\007" +
    "\050\012\056\013\045\017\057\023\047\025\043\001\002" +
    "\000\020\005\044\007\050\012\056\013\045\017\057\023" +
    "\047\025\043\001\002\000\016\006\ufff2\016\ufff2\017\ufff2" +
    "\020\ufff2\021\ufff2\022\ufff2\001\002\000\014\006\ufff0\016" +
    "\ufff0\017\ufff0\020\070\021\067\001\002\000\016\005\044" +
    "\007\050\012\056\013\045\023\047\025\043\001\002\000" +
    "\016\005\044\007\050\012\056\013\045\023\047\025\043" +
    "\001\002\000\014\006\uffed\016\uffed\017\uffed\020\uffed\021" +
    "\uffed\001\002\000\014\006\uffec\016\uffec\017\uffec\020\uffec" +
    "\021\uffec\001\002\000\014\006\uffef\016\uffef\017\uffef\020" +
    "\070\021\067\001\002\000\020\005\044\007\050\012\056" +
    "\013\045\017\076\023\047\025\043\001\002\000\014\006" +
    "\uffe9\016\uffe9\017\uffe9\020\uffe9\021\uffe9\001\002\000\016" +
    "\005\044\007\050\012\056\013\045\023\047\025\043\001" +
    "\002\000\014\006\uffe8\016\uffe8\017\uffe8\020\uffe8\021\uffe8" +
    "\001\002\000\004\014\101\001\002\000\016\002\ufff5\004" +
    "\ufff5\010\ufff5\011\ufff5\015\ufff5\024\ufff5\001\002\000\020" +
    "\005\044\007\050\012\056\013\045\017\057\023\047\025" +
    "\043\001\002\000\010\006\104\016\064\017\063\001\002" +
    "\000\014\006\uffe7\016\uffe7\017\uffe7\020\uffe7\021\uffe7\001" +
    "\002\000\020\005\044\007\050\012\056\013\045\017\057" +
    "\023\047\025\043\001\002\000\010\006\107\016\064\017" +
    "\063\001\002\000\016\006\ufff3\016\ufff3\017\ufff3\020\ufff3" +
    "\021\ufff3\022\ufff3\001\002\000\010\006\111\016\064\017" +
    "\063\001\002\000\016\006\uffe2\016\uffe2\017\uffe2\020\uffe2" +
    "\021\uffe2\022\uffe2\001\002\000\004\002\000\001\002\000" +
    "\016\002\ufffe\004\ufffe\010\ufffe\011\ufffe\015\ufffe\024\ufffe" +
    "\001\002\000\016\002\ufff6\004\ufff6\010\ufff6\011\ufff6\015" +
    "\ufff6\024\ufff6\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\112\000\020\002\007\003\013\010\012\021\006\022" +
    "\005\023\016\025\004\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\013\113\001\001\000\012\003\112\010" +
    "\012\022\005\023\016\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\022\037\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\026\020\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\013\040\001\001\000\002\001\001" +
    "\000\016\011\050\015\054\016\053\017\052\020\051\024" +
    "\045\001\001\000\002\001\001\000\014\015\107\016\053" +
    "\017\052\020\051\024\045\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\017\057" +
    "\020\051\024\045\001\001\000\002\001\001\000\014\015" +
    "\061\016\053\017\052\020\051\024\045\001\001\000\002" +
    "\001\001\000\012\016\072\017\052\020\051\024\045\001" +
    "\001\000\012\016\065\017\052\020\051\024\045\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\017\071\020" +
    "\051\024\045\001\001\000\010\017\070\020\051\024\045" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\017\074\020\051\024\045\001\001\000\002" +
    "\001\001\000\010\017\076\020\051\024\045\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\014" +
    "\015\102\016\053\017\052\020\051\024\045\001\001\000" +
    "\002\001\001\000\002\001\001\000\014\015\105\016\053" +
    "\017\052\020\051\024\045\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



        private String all;
        private String name;
        public String getAll() {
                return all;
        }

        public void setAll(String all) {
                this.all = all;
        }

        public String getName() {
                return name;
        }

        public void setName(String name) {
                this.name = name;
        }
	public String texto(Object o){
		String salida = "";
			try{
				salida = o.toString();
			}
			catch(Exception i){
				salida = "Error";
			}
		return salida;
	}
        public double casteoNumero(Object num) {
                double numero = 0;
                try {
                        String numeroE = num.toString();
                        numero = Double.parseDouble(numeroE);
                } catch (Exception i) {
                        System.err.println("error");
                }

                return numero;

        }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // inicio ::= inicioAprox 
            {
              Object RESULT =null;
		System.out.println("termina mas de uno xD");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // inicio ::= pet 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // inicioAprox ::= inicioAprox inicio1 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("inicioAprox",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // inicioAprox ::= inicio1 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("inicioAprox",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // inicio1 ::= mov 
            {
              Object RESULT =null;
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("inicio1",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // inicio1 ::= push 
            {
              Object RESULT =null;
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("inicio1",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // direccion ::= UP 
            {
              Object RESULT =null;
		int salleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int salright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object sal = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = sal;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("direccion",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // direccion ::= DOWN 
            {
              Object RESULT =null;
		int salleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int salright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object sal = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = sal;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("direccion",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // direccion ::= LEFT 
            {
              Object RESULT =null;
		int salleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int salright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object sal = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = sal;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("direccion",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // direccion ::= RIGHT 
            {
              Object RESULT =null;
		int salleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int salright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object sal = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = sal;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("direccion",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // mov ::= direccion entrada 
            {
              Object RESULT =null;
		int dirleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int dirright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object dir = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int numleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int numright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object num = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                if(texto(dir).equals("up")){
                        if(0<casteoNumero(num)){
                                Movimiento mov = new Movimiento(Direccion.ARRIBA,casteoNumero(num));
                        }
                        else{   
                                Movimiento mov = new Movimiento(Direccion.ABAJO,(casteoNumero(num)*-1));
                        }
                        }
                else if(texto(dir).equals("down")){
                        if(0<casteoNumero(num)){
                                Movimiento mov = new Movimiento(Direccion.ABAJO,casteoNumero(num));
                        }
                        else{   
                                Movimiento mov = new Movimiento(Direccion.ARRIBA,(casteoNumero(num)*-1));
                        }
                        }                       
                else if(texto(dir).equals("left")){

                        if(0<casteoNumero(num)){
                                Movimiento mov = new Movimiento(Direccion.IZQUIERDA,casteoNumero(num));
                        }
                        else{   
                                Movimiento mov = new Movimiento(Direccion.DERECHA,(casteoNumero(num)*-1));
                        }
                                                
                }
                else if(texto(dir).equals("right")){
                        if(0<casteoNumero(num)){
                                Movimiento mov = new Movimiento(Direccion.DERECHA,casteoNumero(num));
                        }
                        else{   
                                Movimiento mov = new Movimiento(Direccion.IZQUIERDA,(casteoNumero(num)*-1));
                        }
                        
                }
              CUP$parser$result = parser.getSymbolFactory().newSymbol("mov",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // entrada ::= PARENTESISABIERTO opNumero PARENTESISCERRADO PUNTOYCOMA 
            {
              Object RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int numright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object num = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		RESULT = num;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("entrada",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // push ::= PUSH direccion entrada 
            {
              Object RESULT =null;
		int dirleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int dirright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object dir = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int numleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int numright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object num = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                if(texto(dir).equals("up")){
                        if(0<casteoNumero(num)){
                                Push push = new Push(Direccion.ARRIBA,casteoNumero(num));
                        }
                        else{   
                                Push push = new Push(Direccion.ABAJO,casteoNumero(num));
                        }
                        }
                else if(texto(dir).equals("down")){
                        if(0<casteoNumero(num)){
                                Push push = new Push(Direccion.ABAJO,casteoNumero(num));
                        }
                        else{   
                                Push push = new Push(Direccion.ARRIBA,casteoNumero(num));
                        }
                        }                       
                else if(texto(dir).equals("left")){

                        if(0<casteoNumero(num)){
                                Push push = new Push(Direccion.IZQUIERDA,casteoNumero(num));
                        }
                        else{   
                                Push push = new Push(Direccion.DERECHA,casteoNumero(num));
                        }
                                                
                }
                else if(texto(dir).equals("right")){
                        if(0<casteoNumero(num)){
                                Push push = new Push(Direccion.DERECHA,casteoNumero(num));
                        }
                        else{   
                                Push push = new Push(Direccion.IZQUIERDA,casteoNumero(num));
                        }
                        
                }
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("push",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // aprox ::= FLOOR PARENTESISABIERTO a PARENTESISCERRADO 
            {
              Object RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int numright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object num = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = (double)num;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("aprox",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // aprox ::= CEIL PARENTESISABIERTO a PARENTESISCERRADO 
            {
              Object RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int numright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object num = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = (double)num;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("aprox",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // opNumero ::= a 
            {
              Object RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int numright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object num = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = (double)num;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("opNumero",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // a ::= a SUMA b 
            {
              Object RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object n1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object n2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = (double)n1 +(double) n2;  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("a",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // a ::= a RESTA b 
            {
              Object RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object n1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object n2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = (double)n1 - (double)n2; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("a",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // a ::= b 
            {
              Object RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object n1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = n1; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("a",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // b ::= b MULTI c 
            {
              Object RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object n1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object n2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = (double)n1 * (double)n2; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("b",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // b ::= b DIV c 
            {
              Object RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object n1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object n2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = (double)n1/(double)n2; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("b",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // b ::= RESTA c 
            {
              Object RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object n1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = -1 *(double) n1; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("b",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // b ::= c 
            {
              Object RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object n1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = (double)n1; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("b",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // c ::= d POTENCIA c 
            {
              Object RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object n1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object n2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("c",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // c ::= d POTENCIA RESTA c 
            {
              Object RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Object n1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object n2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("c",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // c ::= RAIZ PARENTESISABIERTO a PARENTESISCERRADO 
            {
              Object RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object n1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("c",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // c ::= d 
            {
              Object RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object n1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = (double)n1; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("c",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // d ::= NUMERO 
            {
              Object RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object n1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = Double.valueOf(n1.toString());
              CUP$parser$result = parser.getSymbolFactory().newSymbol("d",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // d ::= DECIMAL 
            {
              Object RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object n1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = Double.valueOf(n1.toString());
              CUP$parser$result = parser.getSymbolFactory().newSymbol("d",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // d ::= aprox 
            {
              Object RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object n1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = Double.valueOf(n1.toString());
              CUP$parser$result = parser.getSymbolFactory().newSymbol("d",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // d ::= PARENTESISABIERTO a PARENTESISCERRADO 
            {
              Object RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object n1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = (double)n1; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("d",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // pet ::= LLAVEABIERTA tipo LLAVECERRADA 
            {
              Object RESULT =null;
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("pet",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // tipo ::= COMILLAS WOROLDS COMILLAS DOSPUNTOS COMILLAS ALL COMILLAS 
            {
              Object RESULT =null;
		name = "all";
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // tipo ::= COMILLAS WOROLD COMILLAS DOSPUNTOS COMILLAS ID COMILLAS 
            {
              Object RESULT =null;
		int hleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object h = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		name = texto(h);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
