
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package com.example.boxworld.LexSint;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RAIZ = 17;
  public static final int PUNTOYCOMA = 10;
  public static final int DECIMAL = 19;
  public static final int SUMA = 12;
  public static final int UP = 2;
  public static final int MULTI = 14;
  public static final int POTENCIA = 16;
  public static final int FLOOR = 9;
  public static final int CEIL = 8;
  public static final int PARENTESISCERRADO = 4;
  public static final int RIGHT = 6;
  public static final int PARENTESISABIERTO = 3;
  public static final int LEFT = 18;
  public static final int EOF = 0;
  public static final int DIV = 15;
  public static final int PUSH = 7;
  public static final int error = 1;
  public static final int NUMERO = 5;
  public static final int DOWN = 11;
  public static final int RESTA = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "UP",
  "PARENTESISABIERTO",
  "PARENTESISCERRADO",
  "NUMERO",
  "RIGHT",
  "PUSH",
  "CEIL",
  "FLOOR",
  "PUNTOYCOMA",
  "DOWN",
  "SUMA",
  "RESTA",
  "MULTI",
  "DIV",
  "POTENCIA",
  "RAIZ",
  "LEFT",
  "DECIMAL"
  };
}

