
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package com.mycompany.servidor_boxworold.lexer.cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIAGONAL = 32;
  public static final int NUMERO = 9;
  public static final int DOSPUNTOS = 3;
  public static final int MULTIPLICAR = 33;
  public static final int BRICK_COLOR = 14;
  public static final int NOMBRE = 5;
  public static final int TARGETS = 27;
  public static final int BOX_COLOR = 17;
  public static final int TARGET_COLOR = 19;
  public static final int FLOOR = 42;
  public static final int COLOR_JUGADOR = 12;
  public static final int LLAVECERRADA = 13;
  public static final int CONFIG = 26;
  public static final int PARENTESISCERRADO = 35;
  public static final int BOX_ONT_TAGET_COLOR = 18;
  public static final int TYPE = 25;
  public static final int RAIZ = 37;
  public static final int BOARD = 20;
  public static final int HALL = 38;
  public static final int ID = 8;
  public static final int HALL_COLOR = 15;
  public static final int BRICK = 39;
  public static final int EOF = 0;
  public static final int PLAYER = 28;
  public static final int DECIMAL = 29;
  public static final int COMILLAS = 2;
  public static final int error = 1;
  public static final int COMA = 4;
  public static final int MENOS = 31;
  public static final int CORCHETECERRADO = 22;
  public static final int LLAVEABIERTA = 11;
  public static final int POSY = 24;
  public static final int POTENCIA = 34;
  public static final int POSX = 23;
  public static final int PARENTESISABIERTO = 36;
  public static final int BOXES = 40;
  public static final int FILA = 6;
  public static final int HEXADECIMAL = 10;
  public static final int CEIL = 41;
  public static final int UNDEFINED_COLOR = 16;
  public static final int CORCHETEABIERTO = 21;
  public static final int COLUMNA = 7;
  public static final int MAS = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMILLAS",
  "DOSPUNTOS",
  "COMA",
  "NOMBRE",
  "FILA",
  "COLUMNA",
  "ID",
  "NUMERO",
  "HEXADECIMAL",
  "LLAVEABIERTA",
  "COLOR_JUGADOR",
  "LLAVECERRADA",
  "BRICK_COLOR",
  "HALL_COLOR",
  "UNDEFINED_COLOR",
  "BOX_COLOR",
  "BOX_ONT_TAGET_COLOR",
  "TARGET_COLOR",
  "BOARD",
  "CORCHETEABIERTO",
  "CORCHETECERRADO",
  "POSX",
  "POSY",
  "TYPE",
  "CONFIG",
  "TARGETS",
  "PLAYER",
  "DECIMAL",
  "MAS",
  "MENOS",
  "DIAGONAL",
  "MULTIPLICAR",
  "POTENCIA",
  "PARENTESISCERRADO",
  "PARENTESISABIERTO",
  "RAIZ",
  "HALL",
  "BRICK",
  "BOXES",
  "CEIL",
  "FLOOR"
  };
}

